# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: sunreader2mqtt
version: "1.2.0"
slug: sunreader2mqtt
description: Home Assistant add-on providing Sunreader to MQTT connectivity
url: "https://github.com/thorufur/sunreader2mqtt"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/thorufur/{arch}-addon-sunreader2mqtt"
